


development:
  OPEN_WEATHER_KEY: '8f960837e2msh5d3c11763a419c4p1ce8c9jsn63a831ab8b59' 
  # Paste output of $ rake secret here for your dev machine.

test:

production:
  

  OPEN_WEATHER_KEY: '8f960837e2msh5d3c11763a419c4p1ce8c9jsn63a831ab8b59'